### ISSUE TITLE
Internal error occurred: failed calling webhook "validation.istio.io"

### ISSUE THREAD

**Issue by alice36** [Maistra/istio-operator#1198]
I want to create ServiceMeshControlPlane, all needed operators are succesfully installed but I received this error:

Error processing component mesh-config: error:
mesh-config/templates/enable-mesh-permissive.yaml: Internal error
occurred: failed calling webhook "validation.istio.io": failed to call
webhook: Post
"https://istiod.istio-system.svc:443/validate?timeout=10s": service
"istiod" not found

How to get rid of it?

Uninstall and reinstall of operators is not a fix.
Deleting istio-system namespace and creating one more time is not also a fix.
Creating SMCP on different namespace also ended up with this error.

In which component this information ("https://istiod.istio-system.svc") could be stored?

**Comment by jwendell** [comment]
We don't use GitHub to track issues. Please open an issue here: https://issues.redhat.com/browse/OSSM
