### ISSUE TITLE
any docs to use this operator？

### ISSUE THREAD

**Issue by pennpeng** [Maistra/istio-operator#3]
any docs to use this operator？

**Comment by brian-avery** [comment]
Hi @pennpeng 
We're working on docs over in maistra/maistra.github.io (https://github.com/Maistra/maistra.github.io)

There's a PR for a guide to installing Istio, which discusses the operator. https://github.com/Maistra/maistra.github.io/pull/14/commits/6485aa666771b889ebd0f8ef460185bee50f2f74

**Comment by brian-avery** [comment]
Hi @pennpeng Did this answer your question? Can I close this?

Thanks,
Brian

**Comment by pennpeng** [comment]
thanks a lot
